export const RANKS = [
  { name: "Acolyte",     minXP: 0    },
  { name: "Disciple",    minXP: 1000 },
  { name: "Crusader",    minXP: 2000 },
  { name: "Veteran",     minXP: 3000 },
  { name: "Inquisitor",  minXP: 5000 },
];

export function getRank(xp) {
  for (let i = RANKS.length - 1; i >= 0; i--) {
    if (xp >= RANKS[i].minXP) return RANKS[i].name;
  }
  return RANKS[0].name;
}

// Stat keys now match the new character system
export const INJURY_TABLE = [
  { name: "Lost Eye",     stat: "perception",  penalty: -5, description: "A blade or bullet has claimed your eye. Perception forever diminished." },
  { name: "Lame Leg",     stat: "agility",     penalty: -5, description: "Your leg was shattered. You will never move the same way again." },
  { name: "Scarred Face", stat: "fellowship",  penalty: -5, description: "Your face bears terrible wounds. Others recoil from your visage." },
  { name: "Nerve Damage", stat: "meleeSkill",  penalty: -5, description: "Your sword arm trembles. The nerve damage may never fully heal." },
  { name: "Broken Ribs",  stat: "toughness",   penalty: -5, description: "Your ribs were crushed. Every breath is a reminder of your failure." },
  { name: "Head Wound",   stat: "intelligence",penalty: -5, description: "A blow to the skull has dulled your mind. Some things you will never recall." },
];

export const MISSIONS = [
  {
    id: "assassination_routine",
    name: "Eliminate the Heretic",
    type: "Assassination",
    tier: "Routine",
    flavor: "A low-ranking cult leader has been identified in the underhive. The Inquisition wants him silenced before he can spread his poison further.",
    checks: [
      { stat: "perception",  difficulty: 25, label: "Locate the target",    flavor: "You must find the heretic before he goes to ground.", isCombat: false },
      { stat: "agility",     difficulty: 28, label: "Close the distance",   flavor: "You move through the shadows to get within striking range.", isCombat: false },
      { stat: "meleeSkill",  difficulty: 30, label: "Eliminate the target", flavor: "Steel meets flesh in a brief and brutal exchange.", isCombat: true },
    ],
    xpSuccess: 150,
    xpFailure: 50,
    woundDamageRange: [1, 3],
  },
  {
    id: "assassination_dangerous",
    name: "The Rogue Psyker",
    type: "Assassination",
    tier: "Dangerous",
    flavor: "An unsanctioned psyker has taken refuge in a manufactorum district. His abilities make him unpredictable and lethal. Extreme caution is advised.",
    checks: [
      { stat: "intelligence", difficulty: 35, label: "Research the target",    flavor: "You study what little intelligence exists on the psyker's abilities.", isCombat: false },
      { stat: "willpower",    difficulty: 38, label: "Resist psychic assault", flavor: "The psyker senses your approach and hammers at your mind.", isCombat: false },
      { stat: "meleeSkill",   difficulty: 40, label: "Press the attack",       flavor: "You close in through a storm of psychic fire.", isCombat: true },
      { stat: "rangeSkill",   difficulty: 38, label: "Finish it",              flavor: "A final shot to end the threat before he recovers.", isCombat: true },
    ],
    xpSuccess: 300,
    xpFailure: 100,
    woundDamageRange: [2, 5],
  },
  {
    id: "assassination_deadly",
    name: "The Heretek Magos",
    type: "Assassination",
    tier: "Deadly",
    flavor: "A Magos has turned to dark worship, corrupting an entire forge complex. The Inquisition has sanctioned termination at any cost.",
    checks: [
      { stat: "intelligence", difficulty: 50, label: "Breach the forge complex",       flavor: "The facility is a labyrinth of machines and traps.", isCombat: false },
      { stat: "toughness",    difficulty: 48, label: "Endure the heat and toxins",     flavor: "The forge is a hostile environment designed to kill intruders.", isCombat: false },
      { stat: "meleeSkill",   difficulty: 55, label: "Fight through the servitors",    flavor: "Combat servitors block your path to the Magos.", isCombat: true },
      { stat: "willpower",    difficulty: 52, label: "Resist the dark machine spirit", flavor: "The Magos attempts to seize control of your nervous system.", isCombat: false },
      { stat: "rangeSkill",   difficulty: 55, label: "Execute the Magos",              flavor: "One shot. Make it count.", isCombat: true },
    ],
    xpSuccess: 600,
    xpFailure: 150,
    woundDamageRange: [3, 8],
  },
  {
    id: "infiltration_routine",
    name: "The Smuggler's Den",
    type: "Infiltration",
    tier: "Routine",
    flavor: "A smuggling ring operating out of the docks is suspected of moving forbidden xenos artifacts. Infiltrate and identify the ringleader.",
    checks: [
      { stat: "fellowship",  difficulty: 25, label: "Blend in with the locals", flavor: "You adopt a cover identity among the dock workers.", isCombat: false },
      { stat: "agility",     difficulty: 28, label: "Slip past the guards",     flavor: "A patrol moves through the warehouse. Move quietly.", isCombat: false },
      { stat: "perception",  difficulty: 30, label: "Identify the ringleader",  flavor: "You observe the operation, piecing together who is in charge.", isCombat: false },
    ],
    xpSuccess: 150,
    xpFailure: 50,
    woundDamageRange: [1, 2],
  },
  {
    id: "infiltration_dangerous",
    name: "Cult Initiation",
    type: "Infiltration",
    tier: "Dangerous",
    flavor: "A chaos cult has established itself among the nobility. You must infiltrate their ranks and identify their patron before the next ritual.",
    checks: [
      { stat: "fellowship",  difficulty: 38, label: "Gain entry to the inner circle", flavor: "You must convince a senior cult member of your devotion.", isCombat: false },
      { stat: "willpower",   difficulty: 40, label: "Resist the initiation rite",     flavor: "The cult's rituals test your mental fortitude.", isCombat: false },
      { stat: "intelligence",difficulty: 35, label: "Identify the patron",            flavor: "You piece together clues about who is pulling the strings.", isCombat: false },
      { stat: "agility",     difficulty: 38, label: "Extract without detection",      flavor: "You have what you need. Now get out alive.", isCombat: false },
    ],
    xpSuccess: 300,
    xpFailure: 100,
    woundDamageRange: [1, 4],
  },
  {
    id: "infiltration_deadly",
    name: "Inside the Black Ship",
    type: "Infiltration",
    tier: "Deadly",
    flavor: "A compromised Black Ship carries unsanctioned psykers to an unknown destination. Infiltrate, identify the traitor crew, and prevent catastrophe.",
    checks: [
      { stat: "intelligence", difficulty: 50, label: "Forge the transit papers",     flavor: "Getting aboard requires flawless documentation.", isCombat: false },
      { stat: "willpower",    difficulty: 55, label: "Endure the psychic resonance", flavor: "Hundreds of psykers in close proximity scream at your mind.", isCombat: false },
      { stat: "fellowship",   difficulty: 48, label: "Win the trust of the crew",    flavor: "The traitors are watching everyone. Be beyond suspicion.", isCombat: false },
      { stat: "perception",   difficulty: 52, label: "Identify the traitor",         flavor: "Someone aboard is orchestrating this. Find them.", isCombat: false },
      { stat: "meleeSkill",   difficulty: 55, label: "Confront the traitor",         flavor: "They know you know. There is no way out but through.", isCombat: true },
    ],
    xpSuccess: 600,
    xpFailure: 150,
    woundDamageRange: [2, 7],
  },
  {
    id: "investigation_routine",
    name: "The Missing Adept",
    type: "Investigation",
    tier: "Routine",
    flavor: "An Administratum adept has vanished along with a data-slate containing classified tithe records. Find him before the information falls into the wrong hands.",
    checks: [
      { stat: "intelligence", difficulty: 25, label: "Review the records",       flavor: "You comb through the adept's work for clues.", isCombat: false },
      { stat: "fellowship",   difficulty: 28, label: "Canvass his colleagues",   flavor: "His coworkers may know more than they're letting on.", isCombat: false },
      { stat: "perception",   difficulty: 30, label: "Track his last movements", flavor: "Security pict-feeds and witness accounts paint a picture.", isCombat: false },
    ],
    xpSuccess: 150,
    xpFailure: 50,
    woundDamageRange: [0, 1],
  },
  {
    id: "investigation_dangerous",
    name: "Plague Vector",
    type: "Investigation",
    tier: "Dangerous",
    flavor: "A mysterious sickness is spreading through the lower hive. The symptoms don't match any known disease. Someone is engineering this.",
    checks: [
      { stat: "intelligence", difficulty: 38, label: "Analyse the pathogen",   flavor: "You obtain samples and work to understand what you're dealing with.", isCombat: false },
      { stat: "toughness",    difficulty: 35, label: "Resist infection",        flavor: "Extended exposure to the sick districts takes its toll.", isCombat: false },
      { stat: "perception",   difficulty: 40, label: "Trace the origin point",  flavor: "The spread pattern points toward a source.", isCombat: false },
      { stat: "fellowship",   difficulty: 38, label: "Identify the engineer",   flavor: "Someone created this. You need to find out who.", isCombat: false },
    ],
    xpSuccess: 300,
    xpFailure: 100,
    woundDamageRange: [1, 3],
  },
  {
    id: "investigation_deadly",
    name: "The Daemon Manuscript",
    type: "Investigation",
    tier: "Deadly",
    flavor: "A manuscript of immense daemonic power has surfaced in the scholam archives. Reading it drives men mad. Trace its origin and destroy every copy.",
    checks: [
      { stat: "intelligence", difficulty: 52, label: "Examine the manuscript safely", flavor: "Even indirect study requires extreme mental discipline.", isCombat: false },
      { stat: "willpower",    difficulty: 55, label: "Resist the words",              flavor: "The manuscript seems to read itself to you. Resist.", isCombat: false },
      { stat: "perception",   difficulty: 50, label: "Trace the copies",              flavor: "How many copies exist? Where did they go?", isCombat: false },
      { stat: "intelligence", difficulty: 52, label: "Identify the original author",  flavor: "This was written by someone — or something.", isCombat: false },
      { stat: "willpower",    difficulty: 58, label: "Perform the ritual of unmaking",flavor: "Destroying the manuscript requires speaking its antithesis.", isCombat: false },
    ],
    xpSuccess: 600,
    xpFailure: 150,
    woundDamageRange: [0, 4],
  },
  {
    id: "retrieval_routine",
    name: "Recover the Relic",
    type: "Retrieval",
    tier: "Routine",
    flavor: "A minor Imperial relic has been stolen by a gang of scavengers. Recover it before it disappears into the black market.",
    checks: [
      { stat: "perception", difficulty: 25, label: "Locate the gang's hideout", flavor: "The scavengers have gone to ground. Find them.", isCombat: false },
      { stat: "strength",   difficulty: 28, label: "Force entry",               flavor: "The hideout is barricaded. You make your own door.", isCombat: true },
      { stat: "agility",    difficulty: 30, label: "Recover the relic",         flavor: "In the chaos of the fight, search for the relic.", isCombat: false },
    ],
    xpSuccess: 150,
    xpFailure: 50,
    woundDamageRange: [1, 3],
  },
  {
    id: "retrieval_dangerous",
    name: "The Gene-Seed Cache",
    type: "Retrieval",
    tier: "Dangerous",
    flavor: "A cache of priceless gene-seed has been stolen by xenos raiders. Recovery is of the utmost priority. Casualties are acceptable.",
    checks: [
      { stat: "toughness",  difficulty: 38, label: "Survive the initial assault",  flavor: "The raiders hit hard and fast. Weather the storm.", isCombat: true },
      { stat: "agility",    difficulty: 40, label: "Push through their lines",     flavor: "You fight your way toward the cache location.", isCombat: true },
      { stat: "strength",   difficulty: 35, label: "Break through the final door", flavor: "The cache is sealed behind a bulkhead.", isCombat: false },
      { stat: "willpower",  difficulty: 38, label: "Resist the xenos influence",   flavor: "Something about this place feels deeply wrong.", isCombat: false },
    ],
    xpSuccess: 300,
    xpFailure: 100,
    woundDamageRange: [3, 7],
  },
  {
    id: "retrieval_deadly",
    name: "The Archeotech Vault",
    type: "Retrieval",
    tier: "Deadly",
    flavor: "Deep beneath a dead hive lies an archeotech vault of incalculable value. The last three teams sent never returned.",
    checks: [
      { stat: "toughness",    difficulty: 50, label: "Descend into the dead hive",    flavor: "The environment is toxic, dark, and structurally unstable.", isCombat: false },
      { stat: "intelligence", difficulty: 48, label: "Navigate the ancient systems",  flavor: "The vault's machine spirits are ancient and hostile.", isCombat: false },
      { stat: "strength",     difficulty: 52, label: "Fight through the guardians",   flavor: "Ancient automated defenders still patrol these halls.", isCombat: true },
      { stat: "agility",      difficulty: 55, label: "Survive the vault's defenses",  flavor: "The vault itself tries to kill you as you breach it.", isCombat: true },
      { stat: "toughness",    difficulty: 50, label: "Extract with the archeotech",   flavor: "Getting out carrying the relic is harder than getting in.", isCombat: false },
    ],
    xpSuccess: 600,
    xpFailure: 150,
    woundDamageRange: [4, 10],
  },
];
