export const WEAPON_TYPES = {
  MELEE: "Melee",
  PISTOL: "Pistol",
  BASIC: "Basic",
  HEAVY: "Heavy",
  SPECIAL: "Special",
};

export const WEAPON_CLASS = {
  SOLID_PROJECTILE: "Solid Projectile",
  ENERGY: "Energy",
  EXPLOSIVE: "Explosive",
  FLAMER: "Flamer",
  CHAIN: "Chain",
  POWER: "Power",
  PHASE: "Phase",
  PSYCHIC: "Psychic",
};

export const WEAPON_AVAILABILITY = {
  COMMON: "Common",
  UNCOMMON: "Uncommon",
  RARE: "Rare",
  VERY_RARE: "Very Rare",
  ARCANE: "Arcane",
};

// Proficiency categories (spec Part 2) — used for role proficiency checks and move penalties
export const WEAPON_CATEGORY = {
  PISTOL: "PISTOL",
  RIFLE: "RIFLE",
  CARBINE: "CARBINE",
  LMG: "LMG",
  HMG: "HMG",
  SHOTGUN: "SHOTGUN",
  MARKSMAN: "MARKSMAN",
  FLAMER: "FLAMER",
  MELEE: "MELEE",
  PSYCHIC: "PSYCHIC",
};

export const WEAPONS = [
  // ── Sidearms ─────────────────────────────────────────────────────
  {
    id: "thorn_sidearm",
    name: "Thorn Sidearm",
    type: WEAPON_TYPES.PISTOL,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.PISTOL,
    damage: "1d10",
    pen: 0,
    range: "30m",
    rateOfFire: "S/2/-",
    clip: 12,
    reload: "Half",
    weight: 1.5,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard-issue pistol. Compact, reliable. Every agent carries one.",
    specialRules: ["Reliable"],
    accuracy: 2,
    cost: 15,
  },
  // ── Assault Rifles / Carbines ─────────────────────────────────────
  {
    id: "vex9_rifle",
    name: "Vex-9 Assault Rifle",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.RIFLE,
    damage: "1d10+3",
    pen: 1,
    range: "60m",
    rateOfFire: "S/3/-",
    clip: 30,
    reload: "Half",
    weight: 4,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard workhorse. Reliable, accurate. Named for Vexar Foundries, ninth production iteration.",
    specialRules: ["Reliable", "UB"],
    accuracy: 3,
    cost: 75,
  },
  {
    id: "vex9c_carbine",
    name: "Vex-9C Carbine",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.CARBINE,
    damage: "1d10+2",
    pen: 1,
    range: "40m",
    rateOfFire: "S/3/-",
    clip: 25,
    reload: "Half",
    weight: 3,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Compact variant. Shorter barrel, lighter frame. Designated C for close-pattern.",
    specialRules: ["Reliable"],
    accuracy: 2,
    cost: 60,
  },
  // ── Support Weapons ──────────────────────────────────────────────
  {
    id: "hound_lmg",
    name: "Hound LMG",
    type: WEAPON_TYPES.HEAVY,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.LMG,
    damage: "1d10+4",
    pen: 2,
    range: "80m",
    rateOfFire: "-/-/10",
    clip: 100,
    reload: "Full",
    weight: 10,
    availability: WEAPON_AVAILABILITY.UNCOMMON,
    description: "Squad automatic weapon. Belt-fed, bipod-mounted. Sustained suppressive fire.",
    specialRules: ["Spray", "Bipod"],
    accuracy: 4,
    cost: 200,
  },
  {
    id: "mauler_hmg",
    name: "Mauler HMG",
    type: WEAPON_TYPES.HEAVY,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.HMG,
    damage: "1d10+6",
    pen: 4,
    range: "100m",
    rateOfFire: "-/-/8",
    clip: 80,
    reload: "Full",
    weight: 18,
    availability: WEAPON_AVAILABILITY.RARE,
    description: "Tripod-mounted or braced. Shreds light vehicles and fortifications. Requires setup or exceptional Strength.",
    specialRules: ["Spray", "Bipod", "Brace"],
    accuracy: 4,
    cost: 400,
  },
  // ── Precision ────────────────────────────────────────────────────
  {
    id: "vigil_marksman",
    name: "Vigil Marksman Rifle",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.MARKSMAN,
    damage: "1d10+4",
    pen: 2,
    range: "120m",
    rateOfFire: "S/-/-",
    clip: 10,
    reload: "Half",
    weight: 5,
    availability: WEAPON_AVAILABILITY.UNCOMMON,
    description: "Precision weapon with integrated optics. Semi-automatic, extended range.",
    specialRules: ["Accurate", "Reliable"],
    accuracy: 5,
    cost: 150,
  },
  // ── Shotgun ──────────────────────────────────────────────────────
  {
    id: "reaver_shotgun",
    name: "Reaver Shotgun",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    category: WEAPON_CATEGORY.SHOTGUN,
    damage: "1d10+4",
    pen: 0,
    range: "20m",
    rateOfFire: "S/2/-",
    clip: 8,
    reload: "Full",
    weight: 5,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Close-quarters. Pump-action. Standard shot, breaching slugs, less-lethal shells.",
    specialRules: ["Scatter", "Reliable"],
    accuracy: 1,
    cost: 40,
  },
  // ── Melee ────────────────────────────────────────────────────────
  {
    id: "ashmark_knife",
    name: "Ashmark Combat Knife",
    type: WEAPON_TYPES.MELEE,
    class: WEAPON_CLASS.CHAIN,
    category: WEAPON_CATEGORY.MELEE,
    damage: "1d5+3",
    pen: 1,
    range: "Melee",
    rateOfFire: "-",
    clip: null,
    reload: null,
    weight: 1,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard blade. Carbon-scored kill marks on the handle are traditional.",
    specialRules: [],
    accuracy: 0,
    cost: 10,
  },
  {
    id: "phase_blade",
    name: "Phase Blade",
    type: WEAPON_TYPES.MELEE,
    class: WEAPON_CLASS.PHASE,
    category: WEAPON_CATEGORY.MELEE,
    damage: "1d10+4",
    pen: 3,
    range: "Melee",
    rateOfFire: "-",
    clip: null,
    reload: null,
    weight: 1.5,
    availability: WEAPON_AVAILABILITY.RARE,
    description: "Energy-field blade that treats armor as a suggestion.",
    specialRules: ["Power Field", "Balanced"],
    accuracy: 0,
    cost: 400,
  },
  {
    id: "stun_baton",
    name: "Stun Baton",
    type: WEAPON_TYPES.MELEE,
    class: WEAPON_CLASS.POWER,
    category: WEAPON_CATEGORY.MELEE,
    damage: "1d10+2",
    pen: 0,
    range: "Melee",
    rateOfFire: "-",
    clip: null,
    reload: null,
    weight: 2,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "For taking targets alive and crowd control.",
    specialRules: ["Shocking", "Non-lethal"],
    accuracy: 0,
    cost: 25,
  },
  {
    id: "shield_arm",
    name: "Shield Arm",
    type: WEAPON_TYPES.MELEE,
    class: WEAPON_CLASS.POWER,
    category: WEAPON_CATEGORY.MELEE,
    damage: "1d10+2",
    pen: 0,
    range: "Melee",
    rateOfFire: "-",
    clip: null,
    reload: null,
    weight: 3,
    availability: WEAPON_AVAILABILITY.UNCOMMON,
    description: "Integrated forearm shield with reinforced striking edge. +10 to parry.",
    specialRules: ["Defensive (+10 Parry)", "Shocking"],
    accuracy: 0,
    cost: 150,
  },
  // ── Grenades ─────────────────────────────────────────────────────
  {
    id: "pyre_grenade",
    name: "Pyre Grenade",
    type: WEAPON_TYPES.SPECIAL,
    class: WEAPON_CLASS.EXPLOSIVE,
    damage: "1d10+4",
    pen: 0,
    range: "Thrown",
    rateOfFire: "S/-/-",
    clip: 1,
    reload: null,
    weight: 0.5,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Fragmentation. Named for what remains after detonation.",
    specialRules: ["Blast(3)", "Scatter"],
    accuracy: 0,
    cost: 10,
  },
  {
    id: "lull_grenade",
    name: "Lull Grenade",
    type: WEAPON_TYPES.SPECIAL,
    class: WEAPON_CLASS.EXPLOSIVE,
    damage: "0",
    pen: 0,
    range: "Thrown",
    rateOfFire: "S/-/-",
    clip: 1,
    reload: null,
    weight: 0.5,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Flashbang. Forces a moment of stillness before the squad moves in.",
    specialRules: ["Blast(3)", "Stun"],
    accuracy: 0,
    cost: 10,
  },
  {
    id: "veil_grenade",
    name: "Veil Grenade",
    type: WEAPON_TYPES.SPECIAL,
    class: WEAPON_CLASS.EXPLOSIVE,
    damage: "0",
    pen: 0,
    range: "Thrown",
    rateOfFire: "S/-/-",
    clip: 1,
    reload: null,
    weight: 0.5,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Smoke concealment.",
    specialRules: ["Smoke(3)"],
    accuracy: 0,
    cost: 5,
  },
  // ── Psionic ──────────────────────────────────────────────────────
  {
    id: "aetheric_aperture",
    name: "Aetheric Aperture",
    type: WEAPON_TYPES.PISTOL,
    class: WEAPON_CLASS.PSYCHIC,
    category: WEAPON_CATEGORY.PISTOL,
    damage: "1d10+PsyRating",
    pen: 5,
    range: "30m",
    rateOfFire: "S/-/-",
    clip: null,
    reload: null,
    weight: 1,
    availability: WEAPON_AVAILABILITY.ARCANE,
    description: "Psionic channeling device. Damage scales with Psy Rating. Ignores mundane cover.",
    specialRules: ["Psychic-Powered", "Ignores Cover", "No Ammo"],
    accuracy: 0,
    cost: 0,
  },
  {
    id: "council_focus",
    name: "Council Focus Apparatus",
    type: WEAPON_TYPES.SPECIAL,
    class: WEAPON_CLASS.PSYCHIC,
    category: WEAPON_CATEGORY.PSYCHIC,
    damage: "1d10+PsyRating",
    pen: 3,
    range: "40m",
    rateOfFire: "S/-/-",
    clip: null,
    reload: null,
    weight: 2,
    availability: WEAPON_AVAILABILITY.RARE,
    description: "Crude but functional psionic channeling gauntlet. Monitors output for Council oversight.",
    specialRules: ["Psychic-Powered", "No Ammo"],
    accuracy: 0,
    cost: 0,
  },
  // ── Legacy IDs (aliases for backward compatibility with existing saved data) ──
  {
    id: "laspistol",
    name: "Thorn Sidearm",
    type: WEAPON_TYPES.PISTOL,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    damage: "1d10",
    pen: 0,
    range: "30m",
    rateOfFire: "S/2/-",
    clip: 12,
    reload: "Half",
    weight: 1.5,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard-issue pistol.",
    specialRules: ["Reliable"],
    accuracy: 2,
    cost: 15,
    _legacy: true,
  },
  {
    id: "lasgun",
    name: "Vex-9 Assault Rifle",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    damage: "1d10+3",
    pen: 1,
    range: "60m",
    rateOfFire: "S/3/-",
    clip: 30,
    reload: "Half",
    weight: 4,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard workhorse.",
    specialRules: ["Reliable", "UB"],
    accuracy: 3,
    cost: 75,
    _legacy: true,
  },
  {
    id: "autogun",
    name: "Vex-9C Carbine",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    damage: "1d10+2",
    pen: 1,
    range: "40m",
    rateOfFire: "S/3/-",
    clip: 25,
    reload: "Half",
    weight: 3,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Compact variant.",
    specialRules: ["Reliable"],
    accuracy: 2,
    cost: 60,
    _legacy: true,
  },
  {
    id: "bolt_pistol",
    name: "Thorn Sidearm (Heavy)",
    type: WEAPON_TYPES.PISTOL,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    damage: "1d10+4",
    pen: 3,
    range: "30m",
    rateOfFire: "S/2/-",
    clip: 6,
    reload: "Full",
    weight: 2,
    availability: WEAPON_AVAILABILITY.RARE,
    description: "Heavy-caliber variant of the Thorn.",
    specialRules: ["Explosive", "Tearing"],
    accuracy: 3,
    cost: 150,
    _legacy: true,
  },
  {
    id: "chainknife",
    name: "Ashmark Combat Knife",
    type: WEAPON_TYPES.MELEE,
    class: WEAPON_CLASS.CHAIN,
    damage: "1d5+3",
    pen: 1,
    range: "Melee",
    rateOfFire: "-",
    clip: null,
    reload: null,
    weight: 1,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard blade.",
    specialRules: [],
    accuracy: 0,
    cost: 10,
    _legacy: true,
  },
  {
    id: "power_sword",
    name: "Phase Blade",
    type: WEAPON_TYPES.MELEE,
    class: WEAPON_CLASS.PHASE,
    damage: "1d10+5",
    pen: 5,
    range: "Melee",
    rateOfFire: "-",
    clip: null,
    reload: null,
    weight: 3,
    availability: WEAPON_AVAILABILITY.VERY_RARE,
    description: "Master-crafted phase blade.",
    specialRules: ["Power Field", "Balanced"],
    accuracy: 0,
    cost: 500,
    _legacy: true,
  },
  {
    id: "plasma_pistol",
    name: "Aetheric Aperture",
    type: WEAPON_TYPES.PISTOL,
    class: WEAPON_CLASS.PSYCHIC,
    damage: "1d10+5",
    pen: 4,
    range: "20m",
    rateOfFire: "S/1/-",
    clip: 6,
    reload: "Full",
    weight: 2.5,
    availability: WEAPON_AVAILABILITY.RARE,
    description: "Psionic focusing device.",
    specialRules: ["Psychic-Powered"],
    accuracy: 0,
    cost: 250,
    _legacy: true,
  },
  {
    id: "flamer",
    name: "Pyre Projector",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.FLAMER,
    damage: "1d10+4",
    pen: 4,
    range: "Cone",
    rateOfFire: "S/2/-",
    clip: 6,
    reload: "Full",
    weight: 8,
    availability: WEAPON_AVAILABILITY.RARE,
    description: "Sprays burning accelerant in a cone.",
    specialRules: ["Flamer", "Spray"],
    accuracy: 0,
    cost: 200,
    _legacy: true,
  },
  // Legacy IDs for old class weapons
  {
    id: "assault_rifle",
    name: "Vex-9 Assault Rifle",
    type: WEAPON_TYPES.BASIC,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    damage: "1d10+3",
    pen: 1,
    range: "60m",
    rateOfFire: "S/3/-",
    clip: 30,
    reload: "Half",
    weight: 4,
    availability: WEAPON_AVAILABILITY.COMMON,
    description: "Standard workhorse.",
    specialRules: ["Reliable", "UB"],
    accuracy: 3,
    cost: 75,
    _legacy: true,
  },
  {
    id: "lmg",
    name: "Hound LMG",
    type: WEAPON_TYPES.HEAVY,
    class: WEAPON_CLASS.SOLID_PROJECTILE,
    damage: "1d10+4",
    pen: 2,
    range: "80m",
    rateOfFire: "-/-/10",
    clip: 100,
    reload: "Full",
    weight: 10,
    availability: WEAPON_AVAILABILITY.UNCOMMON,
    description: "Belt-fed suppression weapon.",
    specialRules: ["Spray", "Bipod"],
    accuracy: 4,
    cost: 200,
    _legacy: true,
  },
];

export function getWeaponById(id) {
  return WEAPONS.find(w => w.id === id);
}

export function getWeaponsByType(type) {
  return WEAPONS.filter(w => w.type === type && !w._legacy);
}

export function getWeaponsByAvailability(availability) {
  return WEAPONS.filter(w => w.availability === availability && !w._legacy);
}

export function formatWeaponStats(weapon) {
  let stats = `${weapon.damage} Dmg | Pen ${weapon.pen} | ${weapon.range}`;
  if (weapon.rateOfFire !== "-") {
    stats += ` | RoF ${weapon.rateOfFire}`;
  }
  if (weapon.clip !== null) {
    stats += ` | Clip ${weapon.clip}`;
  }
  return stats;
}
